import '../../../core/services/api_service.dart';
import 'package:uuid/uuid.dart';

enum ServiceType { standard, premium, express, luxury }

enum ServiceStatus { active, inactive, maintenance, suspended }

class Service {
  final String id;
  final String name;
  final String description;
  final ServiceType type;
  ServiceStatus status;
  final double basePrice;
  final int capacity;
  final String route;
  final List<String> features;
  final DateTime createdAt;
  DateTime updatedAt;

  // Van/Bus specific fields
  final String? vehicleNumber;
  final String? vehicleColor;
  final String? driverName;
  final String? drivingExperience;
  final String? driverPhone;
  final String? driverCnic;
  final String? proprietor;
  final String? generalManager;
  final String? manager;
  final String? secretary;
  final String? fromLocation;
  final String? toLocation;
  final String? boardingOffice;
  final String? arrivalOffice;
  final String? departureTime;
  final String? arrivalTime;
  final double? applicationCharges;
  final Map<String, dynamic>? seatLayout;
  final bool? isSeatLayoutConfigured;

  Service({
    required this.id,
    required this.name,
    required this.description,
    required this.type,
    required this.status,
    required this.basePrice,
    required this.capacity,
    required this.route,
    required this.features,
    required this.createdAt,
    required this.updatedAt,
    this.vehicleNumber,
    this.vehicleColor,
    this.driverName,
    this.drivingExperience,
    this.driverPhone,
    this.driverCnic,
    this.proprietor,
    this.generalManager,
    this.manager,
    this.secretary,
    this.fromLocation,
    this.toLocation,
    this.boardingOffice,
    this.arrivalOffice,
    this.departureTime,
    this.arrivalTime,
    this.applicationCharges,
    this.seatLayout,
    this.isSeatLayoutConfigured,
  });

  factory Service.create({
    required String name,
    required String description,
    required ServiceType type,
    required double basePrice,
    required int capacity,
    required String route,
    required List<String> features,
  }) {
    final now = DateTime.now();
    // Note: ID will be generated by database, this is just for local use
    return Service(
      id: const Uuid().v4(),
      name: name,
      description: description,
      type: type,
      status: ServiceStatus.active,
      basePrice: basePrice,
      capacity: capacity,
      route: route,
      features: features,
      createdAt: now,
      updatedAt: now,
    );
  }

  factory Service.fromJson(Map<String, dynamic> json) {
    return Service(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      description: json['description'] ?? '',
      type: ServiceType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => ServiceType.standard,
      ),
      status: ServiceStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => ServiceStatus.active,
      ),
      basePrice: (json['base_price'] ?? 0.0).toDouble(),
      capacity: json['capacity'] ?? 0,
      route:
          json['route_name'] ??
          json['route'] ??
          '', // Handle both route_name and route
      features: List<String>.from(json['features'] ?? []),
      createdAt: DateTime.parse(
        json['created_at'] ?? DateTime.now().toIso8601String(),
      ),
      updatedAt: DateTime.parse(
        json['updated_at'] ?? DateTime.now().toIso8601String(),
      ),

      // Van/Bus specific fields
      vehicleNumber: json['vehicle_number'],
      vehicleColor: json['vehicle_color'],
      driverName: json['driver_name'],
      drivingExperience: json['driving_experience'],
      driverPhone: json['driver_phone'],
      driverCnic: json['driver_cnic'],
      proprietor: json['proprietor'],
      generalManager: json['general_manager'],
      manager: json['manager'],
      secretary: json['secretary'],
      fromLocation: json['from_location'],
      toLocation: json['to_location'],
      boardingOffice: json['boarding_office'],
      arrivalOffice: json['arrival_office'],
      departureTime: json['departure_time'],
      arrivalTime: json['arrival_time'],
      applicationCharges: json['application_charges'] != null
          ? (json['application_charges'] as num).toDouble()
          : null,
      seatLayout: json['seat_layout'],
      isSeatLayoutConfigured: json['is_seat_layout_configured'],
    );
  }
}
